# Generated by Django 5.0.2 on 2025-05-28 23:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='RacaCachorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Raça de Cachorro',
                'verbose_name_plural': 'Raças de Cachorro',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RacaGato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Raça de Gato',
                'verbose_name_plural': 'Raças de Gato',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Vacinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('CACHORRO', 'Cachorro'), ('GATO', 'Gato')], max_length=10)),
                ('dataNascimento', models.DateField(blank=True, null=True)),
                ('idadeEstimada', models.IntegerField(blank=True, help_text='Idade em anos', null=True)),
                ('cor', models.CharField(blank=True, choices=[('PRETO', 'Preto'), ('BRANCO', 'Branco'), ('MARROM', 'Marrom'), ('CINZA', 'Cinza'), ('CARAMELO', 'Caramelo'), ('MESCLADO', 'Mesclado'), ('OUTRO', 'Outro')], max_length=50, null=True)),
                ('comportamento', models.CharField(choices=[('1', 'Dócil'), ('2', 'Agressivo'), ('3', 'Arisco'), ('4', 'Sociável')], max_length=1)),
                ('pelagem', models.CharField(choices=[('1', 'Curta'), ('2', 'Média'), ('3', 'Longa')], max_length=1)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('ADOTADO', 'Adotado')], default='DISPONIVEL', max_length=20)),
                ('genero', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('castrado', models.BooleanField(default=False)),
                ('pertence_instituicao', models.BooleanField(default=True)),
                ('entrada_instituicao', models.DateTimeField(default=django.utils.timezone.now)),
                ('saida_instituicao', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição sobre o animal, seu comportamento, história, etc.', null=True)),
                ('cadastrado_por', models.ForeignKey(blank=True, help_text='Usuário responsável pelo cadastro deste animal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animais_cadastrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['-entrada_instituicao'],
            },
        ),
        migrations.CreateModel(
            name='FotoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='animais/')),
                ('is_principal', models.BooleanField(default=False)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_set', to='core.animal')),
            ],
            options={
                'ordering': ['-is_principal', '-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='Cachorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porte', models.IntegerField(choices=[(1, 'Pequeno'), (2, 'Médio'), (3, 'Grande')])),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.animal')),
                ('raca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.racacachorro')),
            ],
        ),
        migrations.CreateModel(
            name='Gato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.animal')),
                ('raca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.racagato')),
            ],
        ),
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_aplicacao', models.DateField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.animal')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vacinas')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'unique_together': {('user', 'animal')},
            },
        ),
    ]
