# Generated by Django 5.0.2 on 2025-05-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='cor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
