# Generated by Django 5.0.2 on 2025-05-21 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='fotos',
        ),
        migrations.AddField(
            model_name='animal',
            name='tipo',
            field=models.CharField(choices=[('CACHORRO', 'Cachorro'), ('GATO', 'Gato')], default='CACHORRO', max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('ADOTADO', 'Adotado')], default='DISPONIVEL', max_length=20),
        ),
        migrations.AlterField(
            model_name='gato',
            name='raca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.racagato'),
        ),
        migrations.CreateModel(
            name='FotoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='animais/')),
                ('is_principal', models.BooleanField(default=False)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_set', to='core.animal')),
            ],
            options={
                'ordering': ['-is_principal', '-data_upload'],
            },
        ),
    ]
