# Generated by Django 5.0.2 on 2025-05-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_animal_cor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='racacachorro',
            options={'ordering': ['nome'], 'verbose_name': 'Raça de Cachorro', 'verbose_name_plural': 'Raças de Cachorro'},
        ),
        migrations.AlterModelOptions(
            name='racagato',
            options={'ordering': ['nome'], 'verbose_name': 'Raça de Gato', 'verbose_name_plural': 'Raças de Gato'},
        ),
        migrations.AddField(
            model_name='animal',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição sobre o animal, seu comportamento, história, etc.', null=True),
        ),
    ]
