# Generated by Django 5.0.2 on 2025-05-22 00:11

from django.db import migrations, models
from django.utils import timezone

def set_default_entrada(apps, schema_editor):
    Animal = apps.get_model('core', 'Animal')
    for animal in Animal.objects.filter(entrada_instituicao__isnull=True):
        animal.entrada_instituicao = timezone.now()
        animal.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_racacachorro_options_alter_racagato_options_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_entrada),
        migrations.AlterField(
            model_name='animal',
            name='entrada_instituicao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
