# Generated by Django 5.0.2 on 2025-05-22 00:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_animal_entrada_instituicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='sexo_atual',
        ),
        migrations.AlterField(
            model_name='animal',
            name='entrada_instituicao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
