# Generated by Django 5.0.2 on 2025-05-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='cor',
            field=models.CharField(blank=True, choices=[('PRETO', 'Preto'), ('BRANCO', 'Branco'), ('MARROM', 'Marrom'), ('CINZA', 'Cinza'), ('CARAMELO', 'Caramelo'), ('MESCLADO', 'Mesclado'), ('OUTRO', 'Outro')], max_length=50, null=True),
        ),
    ]
