# Generated by Django 5.0.2 on 2025-05-28 00:56

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_animal_cor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adocao',
            options={'ordering': ['-data_requisicao'], 'verbose_name': 'Solicitação de Adoção', 'verbose_name_plural': 'Solicitações de Adoção'},
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['-entrada_instituicao'], 'verbose_name': 'Animal', 'verbose_name_plural': 'Animais'},
        ),
        migrations.AddField(
            model_name='animal',
            name='cadastrado_por',
            field=models.ForeignKey(blank=True, help_text='Usuário responsável pelo cadastro deste animal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animais_cadastrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cachorro',
            name='raca',
            field=models.ForeignKey(default=core.models.RacaCachorro.get_default_raca, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.racacachorro'),
        ),
        migrations.AlterField(
            model_name='gato',
            name='raca',
            field=models.ForeignKey(default=core.models.RacaGato.get_default_raca, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.racagato'),
        ),
    ]
