# Generated by Django 5.0.2 on 2025-05-28 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_adocao_options_alter_animal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adocao',
            options={},
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={},
        ),
        migrations.RemoveField(
            model_name='animal',
            name='cadastrado_por',
        ),
        migrations.AlterField(
            model_name='cachorro',
            name='raca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.racacachorro'),
        ),
        migrations.AlterField(
            model_name='gato',
            name='raca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.racagato'),
        ),
    ]
