# Generated by Django 5.0.2 on 2025-05-29 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profissao',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telefone',
        ),
        migrations.CreateModel(
            name='AdotanteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('profissao', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adotante_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(max_length=9)),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='usuarios.adotanteprofile')),
            ],
        ),
    ]
