# Generated by Django 5.0.2 on 2025-06-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_user_date_joined_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adotanteprofile',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
